config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/search', to: 'home#search'

  devise_for :routes
  devise_for :users

  root to: "home#index"

  resource :books, only: [:new, :create, :destroy] do
    member do
      get 'search'
      post 'shelf'
      post 'search_results'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  attr_accessor :rating

  has_and_belongs_to_many :authors
  has_and_belongs_to_many :genres
  has_many :genres
  has_many :reads
  has_many :authors
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_and_belongs_to_many :books
end

app/models/route.rb
class Route < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_read.rb
class UserRead < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  def new
    @book = Book.new
  end

  def search
    @book = Book.new
  end

  def search_results
    @books = GoogleBooks.search(book_params['title'], {:count => 10})
  end

  def shelf
    binding.pry
  end

  def create
    #@book = Book.create(book_params)
    create_authors(params['authors'])
    @book = Book.find_or_create_by(
      title: params['title'],
      isbn: params['isbn'],
      image_link: params['image_link']
    )
    create_user_read(@book)
    redirect_to root_path
  end

  def destroy
    book = Book.find_by(id: params['id'])
    UserRead.find_by(user: current_user, book: book).destroy
    book.destroy
    current_user.reload
    redirect_to root_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :description, :isbn, :genre_ids => [])
  end

  def create_user_read(book)
    UserRead.create(user: current_user, book: book, rating: 5)
  end

  def create_authors(names)
    Array(names).each do |name|
      Author.find_or_create_by(name: name)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def search
  end
end

app/controllers/user_reads_controller.rb
class UserReadsController < ApplicationController
  def create
    @user_read = UserRead.create(params)
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/books/new.html.erb
<%= render 'shared/add_book' %> 

app/views/books/search.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class='container'>
  <%= simple_form_for @book, :url => search_results_books_path do |f| %>
    <%= f.input :title %>
    <%= f.button :submit, 'Search', class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/books/search_results.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class='container'>
  <p class='text-center  h1' style="color:#694a38;">Search Results</p>
  <div class="card-group">
    <div class="row">
      <% @books.each do |book| %>
        <div class="card m-4" style="max-width: 540px;">
          <div class="row no-gutters">
            <div class="col-md-4">
              <img src="<%= book.image_link %>" class="card-img" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title"><%= book.title %></h5>
                <p class="card-text"><small class="text-muted">By: <%= book.authors %></small></p>
                <p class="card-text"><%=  book.description.truncate(300) %></p>
              </div>
              <div class="card-footer">
                <p class="card-text">Average rating: <%= book.average_rating %>/5</p>
                <p><%= book.isbn %></p>
                <%= button_to "Add",
                  {
                    :controller => :books,
                    :action => "create",
                    :title => book.title,
                    :authors => book.authors,
                    :isbn => book.isbn,
                    :image_link => book.image_link
                  },
                   :method => :post %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<div>

app/views/books/shelf.html.erb
<% binding.pry %>

app/views/home/add_book.html.erb
<% render 'shared/add_book' %>

app/views/home/index.html.erb
<% my_books = UserRead.where(user: current_user) %>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class='container'>
  <p class='text-center  h1' style="color:#694a38;">My Books</p>

  <% my_books.each_slice(5) do |book_slice| %>
    <div class='row mt-5'>
      <% book_slice.each do |user_read| %>
        <% book = Book.find_by(id: user_read.book_id) %>
        <div class='col'>
          <div class="card border-secondary" style="width: 18rem;">
            <img class="card-img-top" src="<%=  book.image_link %>" alt="Card image cap">
            <div class="card-body" style="text-align: center">
              <h5 class="card-title"><%= book.title %></h5>
              <p class="card-text"><%= book.description %></p>
            </div>
            <div style="text-align: center">
            <% if book.genres.count > 0 %>
              <ul class="list-group list-group-flush" style="margin-bottom: 0">
                <% book.genres.each do |genre| %>
                  <li class="list-group-item" style="padding-bottom: 0; padding-top: 0"><%= genre.name %></li>
              <% end %>
              </ul>
            <% end %>
              <% user_read&.rating&.times do %>
                <span class='glyphicon glyphicon-star'></span>
              <% end %>
            </div>
            <div class='card-footer' style="text-align: center">
              <%= button_to 'delete', books_path(:id => book.id), :method => :delete %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/home/search.html.erb
sdsa

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookkeeper</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
  </head>

  <body style="background-color: white;">
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_add_book.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

<div class='container'>
  <%= simple_form_for @book do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.input :isbn %>
    <%= f.label 'Rating (1-5)' %>
    <%= f.range_field :rating, in: 1..5 %>
    <%= f.association :genres, as: :check_boxes %>
    <%= f.association :authors %>
    <%= f.button :submit, class: 'btn btn-secondary' %>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg" style="background-color: #a37774; color: white">
  <span class="navbar-brand">Bookkeeper</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent" style:"color: white;">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" style="color: white;" href="/">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" style="color: white;" href="<%= search_books_path %>">Search</a>
      </li>
    </ul>
  </div>
    <% if user_signed_in? %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link float-right", style:"color:white;" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
        </li>
      </ul>
    <% else %>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
        </li>
    <% end %>
</nav>